locals {
  interfaces_ethernets = flatten([
    for device in local.devices : [
      for int in try(local.device_config[device.name].interfaces.ethernets, []) : {
        key                                     = format("%s/%s", device.name, int.id)
        device                                  = device.name
        id                                      = int.id
        type                                    = "eth"
        access_vlan                             = try(int.access_vlan, local.defaults.nxos.devices.configuration.interfaces.ethernets.access_vlan, 1)
        admin_state                             = try(int.shutdown, local.defaults.nxos.devices.configuration.interfaces.ethernets.shutdown, false)
        auto_negotiation                        = try(int.auto_negotiation, local.defaults.nxos.devices.configuration.interfaces.ethernets.auto_negotiation, null)
        bandwidth                               = try(int.bandwidth, local.defaults.nxos.devices.configuration.interfaces.ethernets.bandwidth, null)
        delay                                   = try(int.delay, local.defaults.nxos.devices.configuration.interfaces.ethernets.delay, null)
        description                             = try(int.description, local.defaults.nxos.devices.configuration.interfaces.ethernets.description, null)
        duplex                                  = try(int.duplex, local.defaults.nxos.devices.configuration.interfaces.ethernets.duplex, null)
        fec_mode                                = try(int.fec_mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.fec_mode, null)
        layer3                                  = try(int.layer3, local.defaults.nxos.devices.configuration.interfaces.ethernets.layer3, false)
        link_debounce_down                      = try(int.link_debounce_down, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_debounce_down, null)
        link_debounce_up                        = try(int.link_debounce_up, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_debounce_up, null)
        link_logging                            = try(int.link_logging, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_logging, null)
        medium                                  = try(int.medium, local.defaults.nxos.devices.configuration.interfaces.ethernets.medium, null)
        mode                                    = try(int.mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.mode, null)
        mtu                                     = try(int.mtu, local.defaults.nxos.devices.configuration.interfaces.ethernets.mtu, null)
        native_vlan                             = try(int.native_vlan, local.defaults.nxos.devices.configuration.interfaces.ethernets.native_vlan, 1)
        speed                                   = try(int.speed, local.defaults.nxos.devices.configuration.interfaces.ethernets.speed, null)
        speed_group                             = try(int.speed_group, local.defaults.nxos.devices.configuration.interfaces.ethernets.speed_group, null)
        trunk_vlans                             = try(int.trunk_vlans, local.defaults.nxos.devices.configuration.interfaces.ethernets.trunk_vlans, null)
        uni_directional_ethernet                = try(int.uni_directional_ethernet, local.defaults.nxos.devices.configuration.interfaces.ethernets.uni_directional_ethernet, null)
        vrf                                     = try(int.vrf, local.defaults.nxos.devices.configuration.interfaces.ethernets.vrf, "default")
        ip_unnumbered                           = try(int.ip_unnumbered, local.defaults.nxos.devices.configuration.interfaces.ethernets.ip_unnumbered, null)
        urpf                                    = try(int.urpf, local.defaults.nxos.devices.configuration.interfaces.ethernets.urpf, null)
        ip_address                              = try(int.ip_address, local.defaults.nxos.devices.configuration.interfaces.ethernets.ip_address, null)
        ospf_process_name                       = try(int.ospf.process, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.process, null)
        ospf_advertise_secondaries              = try(int.ospf.advertise_secondaries, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.advertise_secondaries, false)
        ospf_area                               = try(int.ospf.area, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.area, null)
        ospf_bfd                                = try(int.ospf.bfd, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.bfd, null)
        ospf_cost                               = try(int.ospf.cost, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.cost, null)
        ospf_dead_interval                      = try(int.ospf.dead_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.dead_interval, null)
        ospf_hello_interval                     = try(int.ospf.hello_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.hello_interval, null)
        ospf_network_type                       = try(int.ospf.network_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.network_type, null)
        ospf_passive                            = try(int.ospf.passive, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.passive, null)
        ospf_priority                           = try(int.ospf.priority, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.priority, null)
        ospf_authentication_key                 = try(int.ospf.authentication_key, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.authentication_key, null)
        ospf_authentication_key_id              = try(int.ospf.authentication_key_id, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.authentication_key_id, null)
        ospf_authentication_key_secure_mode     = try(int.ospf.authentication_key_secure_mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.authentication_key_secure_mode, false)
        ospf_authentication_keychain            = try(int.ospf.authentication_keychain, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.authentication_keychain, null)
        ospf_authentication_md5_key             = try(int.ospf.authentication_md5_key, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.authentication_md5_key, null)
        ospf_authentication_md5_key_secure_mode = try(int.ospf.authentication_md5_key_secure_mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.authentication_md5_key_secure_mode, false)
        ospf_authentication_type                = try(int.ospf.authentication_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.authentication_type, null)
        ospf_advertise_subnet                   = try(int.ospf.advertise_subnet, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.advertise_subnet, false)
        ospf_mtu_ignore                         = try(int.ospf.mtu_ignore, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.mtu_ignore, false)
        ospf_node_flag                          = try(int.ospf.node_flag, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.node_flag, null)
        ospf_retransmit_interval                = try(int.ospf.retransmit_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.retransmit_interval, null)
        ospf_transmit_delay                     = try(int.ospf.transmit_delay, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospf.transmit_delay, null)
        ospfv3_process                          = try(int.ospfv3.process, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.process, null)
        ospfv3_advertise_secondaries            = try(int.ospfv3.advertise_secondaries, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.advertise_secondaries, null)
        ospfv3_area                             = try(int.ospfv3.area, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.area, null)
        ospfv3_bfd                              = try(int.ospfv3.bfd, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.bfd, null)
        ospfv3_cost                             = try(int.ospfv3.cost, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.cost, null)
        ospfv3_dead_interval                    = try(int.ospfv3.dead_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.dead_interval, null)
        ospfv3_hello_interval                   = try(int.ospfv3.hello_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.hello_interval, null)
        ospfv3_network_type                     = try(int.ospfv3.network_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.network_type, null)
        ospfv3_passive_interface                = try(int.ospfv3.passive_interface, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.passive_interface, null)
        ospfv3_priority                         = try(int.ospfv3.priority, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.priority, null)
        ospfv3_instance_id                      = try(int.ospfv3.instance_id, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.instance_id, null)
        ospfv3_mtu_ignore                       = try(int.ospfv3.mtu_ignore, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.mtu_ignore, null)
        ospfv3_retransmit_interval              = try(int.ospfv3.retransmit_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.retransmit_interval, null)
        ospfv3_transmit_delay                   = try(int.ospfv3.transmit_delay, local.defaults.nxos.devices.configuration.interfaces.ethernets.ospfv3.transmit_delay, null)
        pim_bfd                                 = try(int.pim.bfd, local.defaults.nxos.devices.configuration.interfaces.ethernets.pim.bfd, null)
        pim_dr_priority                         = try(int.pim.dr_priority, local.defaults.nxos.devices.configuration.interfaces.ethernets.pim.dr_priority, null)
        pim_passive                             = try(int.pim.passive, local.defaults.nxos.devices.configuration.interfaces.ethernets.pim.passive, null)
        pim_sparse_mode                         = try(int.pim.sparse_mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.pim.sparse_mode, null)
        port_channel                            = try(int.port_channel, local.defaults.nxos.devices.configuration.interfaces.ethernets.port_channel, null)
        isis_instance_name                      = try(int.isis.instance_name, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.instance_name, null)
        isis_circuit_type                       = try(int.isis.circuit_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.circuit_type, null)
        isis_ipv4                               = try(int.isis.ipv4, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.ipv4, null)
        isis_ipv6                               = try(int.isis.ipv6, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.ipv6, null)
        isis_network_type_p2p                   = try(int.isis.network_type_p2p, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.network_type_p2p, null)
        isis_passive                            = try(int.isis.passive, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.passive, null)
        isis_metric_l1                          = try(int.isis.metric_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.metric_l1, null)
        isis_metric_l2                          = try(int.isis.metric_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.metric_l2, null)
        isis_ipv6_metric_l1                     = try(int.isis.ipv6_metric_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.ipv6_metric_l1, null)
        isis_ipv6_metric_l2                     = try(int.isis.ipv6_metric_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.ipv6_metric_l2, null)
        isis_priority_l1                        = try(int.isis.priority_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.priority_l1, null)
        isis_priority_l2                        = try(int.isis.priority_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.priority_l2, null)
        isis_hello_interval                     = try(int.isis.hello_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.hello_interval, null)
        isis_hello_interval_l1                  = try(int.isis.hello_interval_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.hello_interval_l1, null)
        isis_hello_interval_l2                  = try(int.isis.hello_interval_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.hello_interval_l2, null)
        isis_hello_multiplier                   = try(int.isis.hello_multiplier, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.hello_multiplier, null)
        isis_hello_multiplier_l1                = try(int.isis.hello_multiplier_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.hello_multiplier_l1, null)
        isis_hello_multiplier_l2                = try(int.isis.hello_multiplier_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.hello_multiplier_l2, null)
        isis_hello_padding                      = try(int.isis.hello_padding, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.hello_padding, null)
        isis_authentication_check               = try(int.isis.authentication_check, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_check, null)
        isis_authentication_check_l1            = try(int.isis.authentication_check_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_check_l1, null)
        isis_authentication_check_l2            = try(int.isis.authentication_check_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_check_l2, null)
        isis_authentication_key                 = try(int.isis.authentication_key, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_key, null)
        isis_authentication_key_l1              = try(int.isis.authentication_key_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_key_l1, null)
        isis_authentication_key_l2              = try(int.isis.authentication_key_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_key_l2, null)
        isis_authentication_type                = try(int.isis.authentication_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_type, null)
        isis_authentication_type_l1             = try(int.isis.authentication_type_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_type_l1, null)
        isis_authentication_type_l2             = try(int.isis.authentication_type_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.authentication_type_l2, null)
        isis_mtu_check                          = try(int.isis.mtu_check, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.mtu_check, null)
        isis_mtu_check_l1                       = try(int.isis.mtu_check_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.mtu_check_l1, null)
        isis_mtu_check_l2                       = try(int.isis.mtu_check_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.mtu_check_l2, null)
        isis_ipv4_bfd                           = try(int.isis.ipv4_bfd, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.ipv4_bfd, null)
        isis_ipv6_bfd                           = try(int.isis.ipv6_bfd, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.ipv6_bfd, null)
        isis_csnp_interval_l1                   = try(int.isis.csnp_interval_l1, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.csnp_interval_l1, null)
        isis_csnp_interval_l2                   = try(int.isis.csnp_interval_l2, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.csnp_interval_l2, null)
        isis_lsp_refresh_interval               = try(int.isis.lsp_refresh_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.lsp_refresh_interval, null)
        isis_retransmit_interval                = try(int.isis.retransmit_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.retransmit_interval, null)
        isis_retransmit_throttle_interval       = try(int.isis.retransmit_throttle_interval, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.retransmit_throttle_interval, null)
        isis_mesh_group_id                      = try(int.isis.mesh_group_id, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.mesh_group_id, null)
        isis_mesh_group_blocked                 = try(int.isis.mesh_group_blocked, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.mesh_group_blocked, null)
        isis_n_flag_clear                       = try(int.isis.n_flag_clear, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.n_flag_clear, null)
        isis_suppressed_state                   = try(int.isis.suppressed_state, local.defaults.nxos.devices.configuration.interfaces.ethernets.isis.suppressed_state, null)
      }
    ]
  ])
}

resource "nxos_physical_interface" "physical_interface" {
  for_each = { for device in local.devices : device.name => device
  if length(try(local.device_config[device.name].interfaces.ethernets, [])) > 0 }
  device = each.key
  physical_interfaces = { for int in try(local.device_config[each.key].interfaces.ethernets, []) : "eth${int.id}" => {
    fec_mode                           = try(int.fec_mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.fec_mode, null)
    access_vlan                        = try(int.port_channel, null) != null ? null : (try(int.layer3, local.defaults.nxos.devices.configuration.interfaces.ethernets.layer3, false) ? "unknown" : "vlan-${try(int.access_vlan, local.defaults.nxos.devices.configuration.interfaces.ethernets.access_vlan, 1)}")
    admin_state                        = try(int.shutdown, local.defaults.nxos.devices.configuration.interfaces.ethernets.shutdown, false) ? "down" : "up"
    auto_negotiation                   = try(int.auto_negotiation, local.defaults.nxos.devices.configuration.interfaces.ethernets.auto_negotiation, null)
    bandwidth                          = try(int.bandwidth, local.defaults.nxos.devices.configuration.interfaces.ethernets.bandwidth, null)
    beacon                             = try(int.beacon, local.defaults.nxos.devices.configuration.interfaces.ethernets.beacon, null) != null ? (try(int.beacon, local.defaults.nxos.devices.configuration.interfaces.ethernets.beacon) ? "on" : "off") : null
    delay                              = try(int.delay, local.defaults.nxos.devices.configuration.interfaces.ethernets.delay, null)
    description                        = try(int.description, local.defaults.nxos.devices.configuration.interfaces.ethernets.description, null)
    dfe_adaptive_tuning                = try(int.dfe_adaptive_tuning, local.defaults.nxos.devices.configuration.interfaces.ethernets.dfe_adaptive_tuning, null) != null ? (try(int.dfe_adaptive_tuning, local.defaults.nxos.devices.configuration.interfaces.ethernets.dfe_adaptive_tuning) ? "enable" : "disable") : null
    dfe_tuning_delay                   = try(int.dfe_tuning_delay, local.defaults.nxos.devices.configuration.interfaces.ethernets.dfe_tuning_delay, null)
    dot1q_ether_type                   = try(int.dot1q_ether_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.dot1q_ether_type, null)
    duplex                             = try(int.duplex, local.defaults.nxos.devices.configuration.interfaces.ethernets.duplex, null)
    equalization_delay                 = try(int.equalization_delay, local.defaults.nxos.devices.configuration.interfaces.ethernets.equalization_delay, null)
    inherit_bandwidth                  = try(int.inherit_bandwidth, local.defaults.nxos.devices.configuration.interfaces.ethernets.inherit_bandwidth, null)
    itu_channel                        = try(int.itu_channel, local.defaults.nxos.devices.configuration.interfaces.ethernets.itu_channel, null)
    layer                              = try(int.port_channel, null) != null ? null : (try(int.layer3, local.defaults.nxos.devices.configuration.interfaces.ethernets.layer3, false) ? "Layer3" : "Layer2")
    link_active_jitter_management      = try(int.link_active_jitter_management, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_active_jitter_management, null) != null ? (try(int.link_active_jitter_management, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_active_jitter_management) ? "enable" : "disable") : null
    link_debounce_down                 = try(int.link_debounce_down, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_debounce_down, null)
    link_debounce_up                   = try(int.link_debounce_up, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_debounce_up, null)
    link_flap_error_disable            = try(int.link_flap_error_disable, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_flap_error_disable, null) != null ? (try(int.link_flap_error_disable, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_flap_error_disable) ? "enable" : "disable") : null
    link_flap_error_max                = try(int.link_flap_error_max, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_flap_error_max, null)
    link_flap_error_seconds            = try(int.link_flap_error_seconds, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_flap_error_seconds, null)
    link_logging                       = try(int.link_logging, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_logging, null) != null ? (try(int.link_logging, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_logging) ? "enable" : "disable") : null
    link_loopback                      = try(int.link_loopback, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_loopback, null) != null ? (try(int.link_loopback, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_loopback) ? "enable" : "disable") : null
    link_mac_up_timer                  = try(int.link_mac_up_timer, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_mac_up_timer, null)
    link_max_bring_up_timer            = try(int.link_max_bring_up_timer, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_max_bring_up_timer, null)
    link_transmit_reset                = try(int.link_transmit_reset, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_transmit_reset, null) != null ? (try(int.link_transmit_reset, local.defaults.nxos.devices.configuration.interfaces.ethernets.link_transmit_reset) ? "enable" : "disable") : null
    mdix                               = try(int.mdix, local.defaults.nxos.devices.configuration.interfaces.ethernets.mdix, null)
    media_type                         = try(int.media_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.media_type, null)
    medium                             = try(int.medium, local.defaults.nxos.devices.configuration.interfaces.ethernets.medium, null)
    mode                               = try(int.mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.mode, null)
    mtu                                = try(int.mtu, local.defaults.nxos.devices.configuration.interfaces.ethernets.mtu, null)
    native_vlan                        = try(int.port_channel, null) != null ? null : (try(int.layer3, local.defaults.nxos.devices.configuration.interfaces.ethernets.layer3, false) ? "unknown" : "vlan-${try(int.native_vlan, local.defaults.nxos.devices.configuration.interfaces.ethernets.native_vlan, 1)}")
    optics_loopback                    = try(int.optics_loopback, local.defaults.nxos.devices.configuration.interfaces.ethernets.optics_loopback, null)
    packet_timestamp_egress_source_id  = try(int.packet_timestamp_egress_source_id, local.defaults.nxos.devices.configuration.interfaces.ethernets.packet_timestamp_egress_source_id, null)
    packet_timestamp_ingress_source_id = try(int.packet_timestamp_ingress_source_id, local.defaults.nxos.devices.configuration.interfaces.ethernets.packet_timestamp_ingress_source_id, null)
    packet_timestamp_state             = try(int.packet_timestamp_state, local.defaults.nxos.devices.configuration.interfaces.ethernets.packet_timestamp_state, null)
    port_type                          = try(int.port_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.port_type, null)
    snmp_trap_state                    = try(int.snmp_trap_link_status, local.defaults.nxos.devices.configuration.interfaces.ethernets.snmp_trap_link_status, null) != null ? (try(int.snmp_trap_link_status, local.defaults.nxos.devices.configuration.interfaces.ethernets.snmp_trap_link_status) ? "enable" : "disable") : null
    span_mode                          = try(int.span_mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.span_mode, null)
    speed                              = try(int.speed, local.defaults.nxos.devices.configuration.interfaces.ethernets.speed, null)
    speed_group                        = try(int.speed_group, local.defaults.nxos.devices.configuration.interfaces.ethernets.speed_group, null)
    squelch                            = try(int.squelch, local.defaults.nxos.devices.configuration.interfaces.ethernets.squelch, null) != null ? (try(int.squelch, local.defaults.nxos.devices.configuration.interfaces.ethernets.squelch) ? "enable" : "disable") : null
    transparent_mode                   = try(int.transparent_mode, local.defaults.nxos.devices.configuration.interfaces.ethernets.transparent_mode, null)
    trunk_logging                      = try(int.trunk_logging, local.defaults.nxos.devices.configuration.interfaces.ethernets.trunk_logging, null) != null ? (try(int.trunk_logging, local.defaults.nxos.devices.configuration.interfaces.ethernets.trunk_logging) ? "enable" : "disable") : null
    trunk_vlans                        = try(int.port_channel, null) != null ? null : (try(int.layer3, local.defaults.nxos.devices.configuration.interfaces.ethernets.layer3, false) ? "1-4094" : try(int.trunk_vlans, local.defaults.nxos.devices.configuration.interfaces.ethernets.trunk_vlans, null))
    uni_directional_ethernet           = try(int.uni_directional_ethernet, local.defaults.nxos.devices.configuration.interfaces.ethernets.uni_directional_ethernet, null)
    user_configured_flags              = try(int.port_channel, null) != null ? null : "admin_layer,admin_mtu,admin_state"
    voice_port_cos                     = try(int.voice_port_cos, local.defaults.nxos.devices.configuration.interfaces.ethernets.voice_port_cos, null)
    voice_port_trust                   = try(int.voice_port_trust, local.defaults.nxos.devices.configuration.interfaces.ethernets.voice_port_trust, null) != null ? (try(int.voice_port_trust, local.defaults.nxos.devices.configuration.interfaces.ethernets.voice_port_trust) ? "enable" : "disable") : null
    voice_vlan_id                      = try(int.voice_vlan, local.defaults.nxos.devices.configuration.interfaces.ethernets.voice_vlan, null)
    voice_vlan_type                    = try(int.voice_vlan_type, local.defaults.nxos.devices.configuration.interfaces.ethernets.voice_vlan_type, null)
    vrf_dn                             = try(int.port_channel, null) != null ? null : (try(int.layer3, local.defaults.nxos.devices.configuration.interfaces.ethernets.layer3, false) ? "sys/inst-${try(int.vrf, local.defaults.nxos.devices.configuration.interfaces.ethernets.vrf, "default")}" : null)
  } }

  depends_on = [
    nxos_vrf.vrf,
  ]
}
