resource "nxos_snmp" "snmp" {
  for_each = { for device in local.devices : device.name => device
  if try(local.device_config[device.name].snmp, null) != null }
  device                                                = each.key
  contact                                               = try(local.device_config[each.key].snmp.contact, null)
  location                                              = try(local.device_config[each.key].snmp.location, null)
  engine_id                                             = try(local.device_config[each.key].snmp.engine_id, null)
  logging_level                                         = try(local.device_config[each.key].snmp.logging_level, null)
  packet_size                                           = try(local.device_config[each.key].snmp.packetsize, null)
  enforce_privacy                                       = try(local.device_config[each.key].snmp.global_enforce_priv, null) == null ? null : (try(local.device_config[each.key].snmp.global_enforce_priv) ? "yes" : "no")
  tcp_session_authentication                            = try(local.device_config[each.key].snmp.tcp_session_auth, null) == null ? null : (try(local.device_config[each.key].snmp.tcp_session_auth) ? "tcpSessAuth" : "no")
  source_interface_traps                                = try(local.device_config[each.key].snmp.source_interface_type, null) != null ? "${local.intf_prefix_map[try(local.device_config[each.key].snmp.source_interface_type)]}${try(local.device_config[each.key].snmp.source_interface_id, "")}" : null
  enable_all                                            = try(local.device_config[each.key].snmp.enable_traps, null) == null ? null : (try(local.device_config[each.key].snmp.enable_traps) ? "yes" : "no")
  aaa_server_state_change_trap_status                   = try(local.device_config[each.key].snmp.traps.aaa_server_state_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.aaa_server_state_change) ? "enable" : "disable")
  bfd_session_down_trap_status                          = try(local.device_config[each.key].snmp.traps.bfd_session_down, null) == null ? null : (try(local.device_config[each.key].snmp.traps.bfd_session_down) ? "enable" : "disable")
  bfd_session_up_trap_status                            = try(local.device_config[each.key].snmp.traps.bfd_session_up, null) == null ? null : (try(local.device_config[each.key].snmp.traps.bfd_session_up) ? "enable" : "disable")
  bridge_new_root_trap_status                           = try(local.device_config[each.key].snmp.traps.bridge_newroot, null) == null ? null : (try(local.device_config[each.key].snmp.traps.bridge_newroot) ? "enable" : "disable")
  bridge_topology_change_trap_status                    = try(local.device_config[each.key].snmp.traps.bridge_topology_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.bridge_topology_change) ? "enable" : "disable")
  callhome_event_notify_trap_status                     = try(local.device_config[each.key].snmp.traps.callhome_event_notify, null) == null ? null : (try(local.device_config[each.key].snmp.traps.callhome_event_notify) ? "enable" : "disable")
  callhome_smtp_send_fail_trap_status                   = try(local.device_config[each.key].snmp.traps.callhome_smtp_send_fail, null) == null ? null : (try(local.device_config[each.key].snmp.traps.callhome_smtp_send_fail) ? "enable" : "disable")
  cfs_state_change_notif_trap_status                    = try(local.device_config[each.key].snmp.traps.cfs_state_change_notif, null) == null ? null : (try(local.device_config[each.key].snmp.traps.cfs_state_change_notif) ? "enable" : "disable")
  cfs_merge_failure_trap_status                         = try(local.device_config[each.key].snmp.traps.cfs_merge_failure, null) == null ? null : (try(local.device_config[each.key].snmp.traps.cfs_merge_failure) ? "enable" : "disable")
  config_cli_running_config_change_trap_status          = try(local.device_config[each.key].snmp.traps.config_ccm_cli_running_config_changed, null) == null ? null : (try(local.device_config[each.key].snmp.traps.config_ccm_cli_running_config_changed) ? "enable" : "disable")
  entity_mib_change_trap_status                         = try(local.device_config[each.key].snmp.traps.entity_mib_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_mib_change) ? "enable" : "disable")
  entity_mib_enable_status_notification_trap_status     = try(local.device_config[each.key].snmp.traps.entity_cefc_mib_enable_status_notification, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_cefc_mib_enable_status_notification) ? "enable" : "disable")
  entity_fan_status_change_trap_status                  = try(local.device_config[each.key].snmp.traps.entity_fan_status_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_fan_status_change) ? "enable" : "disable")
  entity_module_inserted_trap_status                    = try(local.device_config[each.key].snmp.traps.entity_module_inserted, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_module_inserted) ? "enable" : "disable")
  entity_module_removed_trap_status                     = try(local.device_config[each.key].snmp.traps.entity_module_removed, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_module_removed) ? "enable" : "disable")
  entity_module_status_change_trap_status               = try(local.device_config[each.key].snmp.traps.entity_module_status_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_module_status_change) ? "enable" : "disable")
  entity_power_out_change_trap_status                   = try(local.device_config[each.key].snmp.traps.entity_power_out_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_power_out_change) ? "enable" : "disable")
  entity_power_status_change_trap_status                = try(local.device_config[each.key].snmp.traps.entity_power_status_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_power_status_change) ? "enable" : "disable")
  entity_sensor_trap_status                             = try(local.device_config[each.key].snmp.traps.entity_sensor, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_sensor) ? "enable" : "disable")
  entity_unrecognised_module_trap_status                = try(local.device_config[each.key].snmp.traps.entity_unrecognised_module, null) == null ? null : (try(local.device_config[each.key].snmp.traps.entity_unrecognised_module) ? "enable" : "disable")
  fcdomain_domain_id_not_assigned_trap_status           = try(local.device_config[each.key].snmp.traps.fcdomain_domain_id_not_assigned, null) == null ? null : (try(local.device_config[each.key].snmp.traps.fcdomain_domain_id_not_assigned) ? "enable" : "disable")
  fcdomain_fabric_change_trap_status                    = try(local.device_config[each.key].snmp.traps.fcdomain_fabric_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.fcdomain_fabric_change) ? "enable" : "disable")
  fcdomain_new_principal_switch_trap_status             = try(local.device_config[each.key].snmp.traps.fcdomain_new_principal_switch, null) == null ? null : (try(local.device_config[each.key].snmp.traps.fcdomain_new_principal_switch) ? "enable" : "disable")
  feature_control_op_status_change_trap_status          = try(local.device_config[each.key].snmp.traps.feature_control_feature_op_status_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.feature_control_feature_op_status_change) ? "enable" : "disable")
  feature_control_cisco_op_status_change_trap_status    = try(local.device_config[each.key].snmp.traps.feature_control_cisco_feat_op_status_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.feature_control_cisco_feat_op_status_change) ? "enable" : "disable")
  generic_cold_start_trap_status                        = try(local.device_config[each.key].snmp.traps.generic_cold_start, null) == null ? null : (try(local.device_config[each.key].snmp.traps.generic_cold_start) ? "enable" : "disable")
  generic_warm_start_trap_status                        = try(local.device_config[each.key].snmp.traps.generic_warm_start, null) == null ? null : (try(local.device_config[each.key].snmp.traps.generic_warm_start) ? "enable" : "disable")
  hsrp_state_change_trap_status                         = try(local.device_config[each.key].snmp.traps.hsrp_state_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.hsrp_state_change) ? "enable" : "disable")
  license_expiry_trap_status                            = try(local.device_config[each.key].snmp.traps.license_notify_license_expiry, null) == null ? null : (try(local.device_config[each.key].snmp.traps.license_notify_license_expiry) ? "enable" : "disable")
  license_expiry_warning_trap_status                    = try(local.device_config[each.key].snmp.traps.license_notify_license_expiry_warning, null) == null ? null : (try(local.device_config[each.key].snmp.traps.license_notify_license_expiry_warning) ? "enable" : "disable")
  license_file_missing_trap_status                      = try(local.device_config[each.key].snmp.traps.license_notify_license_file_missing, null) == null ? null : (try(local.device_config[each.key].snmp.traps.license_notify_license_file_missing) ? "enable" : "disable")
  license_no_license_for_feature_trap_status            = try(local.device_config[each.key].snmp.traps.license_notify_no_license_for_feature, null) == null ? null : (try(local.device_config[each.key].snmp.traps.license_notify_no_license_for_feature) ? "enable" : "disable")
  link_cie_link_down_trap_status                        = try(local.device_config[each.key].snmp.traps.link_cie_link_down, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_cie_link_down) ? "enable" : "disable")
  link_cie_link_up_trap_status                          = try(local.device_config[each.key].snmp.traps.link_cie_link_up, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_cie_link_up) ? "enable" : "disable")
  link_cisco_xcvr_mon_status_change_trap_status         = try(local.device_config[each.key].snmp.traps.link_cisco_xcvr_mon_status_chg, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_cisco_xcvr_mon_status_chg) ? "enable" : "disable")
  link_cmn_mac_move_notification_trap_status            = try(local.device_config[each.key].snmp.traps.link_cmn_mac_move_notification, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_cmn_mac_move_notification) ? "enable" : "disable")
  link_delayed_link_state_change_trap_status            = try(local.device_config[each.key].snmp.traps.link_delayed_link_state_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_delayed_link_state_change) ? "enable" : "disable")
  link_extended_link_down_trap_status                   = try(local.device_config[each.key].snmp.traps.link_extended_link_down, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_extended_link_down) ? "enable" : "disable")
  link_extended_link_up_trap_status                     = try(local.device_config[each.key].snmp.traps.link_extended_link_up, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_extended_link_up) ? "enable" : "disable")
  link_link_down_trap_status                            = try(local.device_config[each.key].snmp.traps.link_link_down, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_link_down) ? "enable" : "disable")
  link_link_up_trap_status                              = try(local.device_config[each.key].snmp.traps.link_link_up, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_link_up) ? "enable" : "disable")
  link_err_disable_interface_event_trap_status          = try(local.device_config[each.key].snmp.traps.link_err_disable_interface_event_rev1, null) == null ? null : (try(local.device_config[each.key].snmp.traps.link_err_disable_interface_event_rev1) ? "enable" : "disable")
  lldp_rem_tables_change_trap_status                    = try(local.device_config[each.key].snmp.traps.lldp_rem_tables_change, null) == null ? null : (try(local.device_config[each.key].snmp.traps.lldp_rem_tables_change) ? "enable" : "disable")
  mmode_maint_mode_change_trap_status                   = try(local.device_config[each.key].snmp.traps.mmode_cse_maint_mode_change_notify, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mmode_cse_maint_mode_change_notify) ? "enable" : "disable")
  mmode_normal_mode_change_trap_status                  = try(local.device_config[each.key].snmp.traps.mmode_cse_normal_mode_change_notify, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mmode_cse_normal_mode_change_notify) ? "enable" : "disable")
  mpls_ldp_trap_status                                  = try(local.device_config[each.key].snmp.traps.mpls_ldp, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_ldp) ? "enable" : "disable")
  mpls_ldp_session_down_trap_status                     = try(local.device_config[each.key].snmp.traps.mpls_ldp_session_down, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_ldp_session_down) ? "enable" : "disable")
  mpls_ldp_session_up_trap_status                       = try(local.device_config[each.key].snmp.traps.mpls_ldp_session_up, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_ldp_session_up) ? "enable" : "disable")
  mpls_vpn_trap_status                                  = try(local.device_config[each.key].snmp.traps.mpls_vpn, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_vpn) ? "enable" : "disable")
  mpls_vpn_max_thresh_cleared_trap_status               = try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_max_thresh_cleared, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_max_thresh_cleared) ? "enable" : "disable")
  mpls_vpn_max_thresh_exceeded_trap_status              = try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_max_thresh_exceeded, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_max_thresh_exceeded) ? "enable" : "disable")
  mpls_vpn_mid_thresh_exceeded_trap_status              = try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_mid_thresh_exceeded, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_mid_thresh_exceeded) ? "enable" : "disable")
  mpls_vpn_vrf_down_trap_status                         = try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_down, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_down) ? "enable" : "disable")
  mpls_vpn_vrf_up_trap_status                           = try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_up, null) == null ? null : (try(local.device_config[each.key].snmp.traps.mpls_vpn_vrf_up) ? "enable" : "disable")
  msdp_backward_transition_trap_status                  = try(local.device_config[each.key].snmp.traps.msdp_backward_transition, null) == null ? null : (try(local.device_config[each.key].snmp.traps.msdp_backward_transition) ? "enable" : "disable")
  pim_neighbor_loss_trap_status                         = try(local.device_config[each.key].snmp.traps.pim_neighbor_loss, null) == null ? null : (try(local.device_config[each.key].snmp.traps.pim_neighbor_loss) ? "enable" : "disable")
  port_security_access_secure_mac_violation_trap_status = try(local.device_config[each.key].snmp.traps.port_security_access_secure_mac_violation, null) == null ? null : (try(local.device_config[each.key].snmp.traps.port_security_access_secure_mac_violation) ? "enable" : "disable")
  port_security_trunk_secure_mac_violation_trap_status  = try(local.device_config[each.key].snmp.traps.port_security_trunk_secure_mac_violation, null) == null ? null : (try(local.device_config[each.key].snmp.traps.port_security_trunk_secure_mac_violation) ? "enable" : "disable")
  rf_redundancy_framework_trap_status                   = try(local.device_config[each.key].snmp.traps.rf_redundancy_framework, null) == null ? null : (try(local.device_config[each.key].snmp.traps.rf_redundancy_framework) ? "enable" : "disable")
  rmon_rising_alarm_trap_status                         = try(local.device_config[each.key].snmp.traps.rmon_rising_alarm, null) == null ? null : (try(local.device_config[each.key].snmp.traps.rmon_rising_alarm) ? "enable" : "disable")
  rmon_falling_alarm_trap_status                        = try(local.device_config[each.key].snmp.traps.rmon_falling_alarm, null) == null ? null : (try(local.device_config[each.key].snmp.traps.rmon_falling_alarm) ? "enable" : "disable")
  rmon_hc_rising_alarm_trap_status                      = try(local.device_config[each.key].snmp.traps.rmon_hc_rising_alarm, null) == null ? null : (try(local.device_config[each.key].snmp.traps.rmon_hc_rising_alarm) ? "enable" : "disable")
  rmon_hc_falling_alarm_trap_status                     = try(local.device_config[each.key].snmp.traps.rmon_hc_falling_alarm, null) == null ? null : (try(local.device_config[each.key].snmp.traps.rmon_hc_falling_alarm) ? "enable" : "disable")
  snmp_authentication_trap_status                       = try(local.device_config[each.key].snmp.traps.snmp_authentication, null) == null ? null : (try(local.device_config[each.key].snmp.traps.snmp_authentication) ? "enable" : "disable")
  storm_control_cpsc_event_trap_status                  = try(local.device_config[each.key].snmp.traps.storm_control_cpsc_event_rev1, null) == null ? null : (try(local.device_config[each.key].snmp.traps.storm_control_cpsc_event_rev1) ? "enable" : "disable")
  stpx_inconsistency_trap_status                        = try(local.device_config[each.key].snmp.traps.stpx_inconsistency, null) == null ? null : (try(local.device_config[each.key].snmp.traps.stpx_inconsistency) ? "enable" : "disable")
  stpx_loop_inconsistency_trap_status                   = try(local.device_config[each.key].snmp.traps.stpx_loop_inconsistency, null) == null ? null : (try(local.device_config[each.key].snmp.traps.stpx_loop_inconsistency) ? "enable" : "disable")
  stpx_root_inconsistency_trap_status                   = try(local.device_config[each.key].snmp.traps.stpx_root_inconsistency, null) == null ? null : (try(local.device_config[each.key].snmp.traps.stpx_root_inconsistency) ? "enable" : "disable")
  syslog_message_generated_trap_status                  = try(local.device_config[each.key].snmp.traps.syslog_message_generated, null) == null ? null : (try(local.device_config[each.key].snmp.traps.syslog_message_generated) ? "enable" : "disable")
  sysmgr_fail_sw_core_notify_trap_status                = try(local.device_config[each.key].snmp.traps.sysmgr_cse_fail_sw_core_notify_extended, null) == null ? null : (try(local.device_config[each.key].snmp.traps.sysmgr_cse_fail_sw_core_notify_extended) ? "enable" : "disable")
  system_clock_change_notification_trap_status          = try(local.device_config[each.key].snmp.traps.system_clock_change_notification, null) == null ? null : (try(local.device_config[each.key].snmp.traps.system_clock_change_notification) ? "enable" : "disable")
  upgrade_job_status_notify_trap_status                 = try(local.device_config[each.key].snmp.traps.upgrade_job_status_notify, null) == null ? null : (try(local.device_config[each.key].snmp.traps.upgrade_job_status_notify) ? "enable" : "disable")
  upgrade_op_notify_on_completion_trap_status           = try(local.device_config[each.key].snmp.traps.upgrade_op_notify_on_completion, null) == null ? null : (try(local.device_config[each.key].snmp.traps.upgrade_op_notify_on_completion) ? "enable" : "disable")
  vtp_notifs_trap_status                                = try(local.device_config[each.key].snmp.traps.vtp_notifs, null) == null ? null : (try(local.device_config[each.key].snmp.traps.vtp_notifs) ? "enable" : "disable")
  vtp_vlan_create_trap_status                           = try(local.device_config[each.key].snmp.traps.vtp_vlan_create, null) == null ? null : (try(local.device_config[each.key].snmp.traps.vtp_vlan_create) ? "enable" : "disable")
  vtp_vlan_delete_trap_status                           = try(local.device_config[each.key].snmp.traps.vtp_vlan_delete, null) == null ? null : (try(local.device_config[each.key].snmp.traps.vtp_vlan_delete) ? "enable" : "disable")
  local_users = { for user in try(local.device_config[each.key].snmp.users, []) : user.name => {
    authentication_password = try(user.authentication_password, null)
    authentication_type     = try(user.authentication_type, null)
    ipv4_acl_name           = try(user.ipv4_acl, null)
    ipv6_acl_name           = try(user.ipv6_acl, null)
    enforce_privacy         = try(user.enforce_privacy, null)
    localized_v2_key        = try(user.localized_v2_key, null)
    localized_key           = try(user.localized_key, null)
    privacy_password        = try(user.privacy_password, null)
    privacy_type            = try(user.privacy_type, null)
    engine_id               = try(user.engine_id, null)
    groups                  = { for group in try(user.groups, []) : group => {} }
  } }
  hosts = { for host in try(local.device_config[each.key].snmp.hosts, []) : "${host.host};${try(host.udp_port, 162)}" => {
    community_name    = try(host.community, null)
    notification_type = try(host.notification_type, null)
    security_level    = try(host.security_level, null)
    version           = try(host.version, null)
    vrfs              = try(host.vrf, null) != null ? { (host.vrf) = {} } : {}
  } }
  rmon_events = { for event in try(local.device_config[each.key].snmp.rmon_events, []) : event.number => {
    description = try(event.description, null)
    log         = try(event.log, null) == null ? null : (try(event.log) ? "yes" : "no")
    owner       = try(event.owner, null)
    trap        = try(event.trap, null)
  } }

  depends_on = [
    nxos_feature.feature,
  ]
}
